### PR TITLE
run tests in CI

### PR DESCRIPTION
**Pull request by miraclx**
Run the tests in `src/token.js` and `src/uniswap.js` in CI.

### CODE REVIEW

**Comment by miraclx** [comment]
Also updated the uniswap script to be a testing lib when executed directly.

CleanShot 2022-09-20 at 15 08 11@2x

**Comment by Khadeeejah** [comment]
HI  @miraclx The shasum is conflicting, i think its because of the previous build. i guess you can update this with the last one i merged

**Comment by Khadeeejah** [comment]
Did you forget to run "yarn-lint" @miraclx

**Comment by miraclx** [comment]
That wasn't the issue, the lint script needed the bundle to be prebuilt, so `yarn build` must always precede `yarn lint`. Fixed.

Although, to fix the other test, you have to add the infura token to GH secrets.

**Comment by miraclx** [comment]
Didn't work because secrets aren't passed to workflow runs from forks.

https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

Trying something else in #5.

**Pull request merged**
